GYM Management System/Models/Client.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Attendences = new HashSet<Attendence>();
            this.ClientBills = new HashSet<ClientBill>();
            this.ClientServiceLists = new HashSet<ClientServiceList>();
            this.FoodPlans = new HashSet<FoodPlan>();
            this.Schedules = new HashSet<Schedule>();
            this.Sells = new HashSet<Sell>();
        }
    
        public int ClientId { get; set; }
        public string ClietName { get; set; }
        public int ClientIdNumber { get; set; }
        public string ClientContact { get; set; }
        public string ClientMail { get; set; }
        public string ClientAddress { get; set; }
        public System.DateTime ClientGymStart { get; set; }
        public string ClientUserName { get; set; }
        public string ClientPassword { get; set; }
        public int ClientAdmitionfee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence> Attendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBill> ClientBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceList> ClientServiceLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodPlan> FoodPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sells { get; set; }
    }
}

GYM Management System/Models/ClientServiceList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceList
    {
        public int ClientServiceListId { get; set; }
        public int ClientId { get; set; }
        public int ServiceId { get; set; }
        public bool Service_Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Servicess Servicess { get; set; }
    }
}

GYM Management System/Models/Validation/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GYM_Management_System.Models
{
    [MetadataType(typeof(MetadataClient))]
    public partial class Client
    {
    }

    public class MetadataClient
        {
        [Required]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage  = "Name is not correct format")]

        //[MinLength(5, ErrorMessage = "User Name can't be less than 5 characters")]
        [MaxLength(50, ErrorMessage = "User name can't be more than 50 characters")]
        [Display(Name = "Client Name")]
        public string ClietName { get; set; }

        [Required]
        //[MinLength(3, ErrorMessage="User ID can't be less than 3 characters")]
        //[MaxLength(10, ErrorMessage = "User ID can't be more than 10 characters")]
        [Display(Name = "Client ID")]
        
        public int ClientIdNumber { get; set; }

        [Required]
        [MinLength(6, ErrorMessage = "User Contact can't be less than 6 characters")]
        [MaxLength(11, ErrorMessage = "User Contact can't be more than 11 characters")]
        [Display(Name = "Contact")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"\d+", ErrorMessage = "Name is not correct format")]
        public string ClientContact { get; set; }

        [Required]
        //[MinLength(12, ErrorMessage = "User E-mail can't be less than 12 characters")]
        [MaxLength(100, ErrorMessage = "User E-mail can't be more than 100 characters")]
        [Display(Name = "E-mail")]
        [DataType(DataType.EmailAddress)]
        public string ClientMail { get; set; }

        [Required]
        //[MinLength(10, ErrorMessage = "User Address can't be less than 10 characters")]
        [MaxLength(100, ErrorMessage = "User Address can't be more than 100 characters")]
        [Display(Name = "Address")]
        public string ClientAddress { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime ClientGymStart { get; set; }

        [Required]
        //[MinLength(10, ErrorMessage = "User User Name can't be less than 10 characters")]
        [MaxLength(50, ErrorMessage = "User User Name can't be more than 50 characters")]
        [Display(Name = "Username")]
        public string ClientUserName { get; set; }

        [Required]
        //[MinLength(4, ErrorMessage = "User Password can't be less than 10 characters")]
        [MaxLength(50, ErrorMessage = "User Password can't be more than 50 characters")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string ClientPassword { get; set; }

        [Required]
        [Display(Name = "Registration Fee")]
        //[MinLength(3, ErrorMessage = "User Registration Free can't be less than 3 characters")]
        //[MaxLength(5, ErrorMessage = "User Registration Free can't be more than 5 characters")]
        public int ClientAdmitionfee { get; set; }
     
}
}

GYM Management System/Models/Validation/ClientServiceList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GYM_Management_System.Models
{
    [MetadataType(typeof(MetadataClientServiceList))]
    public partial class ClientServiceList
    {
    }

    public class MetadataClientServiceList
    {
        [Required]
        //[MinLength(5, ErrorMessage = "User Client Name can't be less than 5 characters")]
        //[MaxLength(20, ErrorMessage = "User Client Name can't be more than 20 characters")]
        [Display(Name ="Client Name")]
        public int ClientId { get; set; }

        //[MinLength(10, ErrorMessage = "User Service Name can't be less than 10 characters")]
        //[MaxLength(30, ErrorMessage = "User Service name can't be more than 30 characters")]
        [Required]
        [Display(Name ="Service Name")]
        public int ServiceId { get; set; }

    }
}

GYM Management System/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using GYM_Management_System.Models;

namespace GYM_Management_System.Controllers
{
    public class ClientController : Controller
    {
        gym_managementEntities db = new gym_managementEntities();
       
        // GET: Clienti
        public ActionResult Index()
        {
            return View();
        }
        
        // Client Registration Start .....

        public ActionResult ClientRegistration()
        {
            int a = Convert.ToInt32(Session["id"]);
            int b = Convert.ToInt32(Session["Designation"]);
            if (a != 0 && b == 1)
            {
                //List<Servicess> serviceList = db.Servicesses.ToList();
                //serviceList.Add(new Servicess() { ServiceId = 0, ServiceName = "Select One" });
                ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
                ViewBag.ScheduleTimeId = new SelectList(db.ScheduleTimes, "ScheduleTimeId", "ScheduleName");
                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                return View();
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        [HttpPost]
        public ActionResult ClientRegistration(Client client, int? ServiceId, int? ClientIdNumber,string ClientPassword, int? EmployeeId, int? ScheduleTimeId)
        {
            int er = 0;
            if (ServiceId==null)
            {
                ViewBag.ename = "Select Service Name";
                er++;
            }
            if (ClientPassword == "")
            {
                er++;
                ViewBag.password = "Password Required";
            }
            if (EmployeeId == null)
            {
                er++;
                ViewBag.Employee = "Select Employee Name ";
            }
            if (ScheduleTimeId == null)
            {
                er++;
                ViewBag.ScheduleTime = "Select Schedule Name ";
            }
            bool isThisIdExist = db.Clients.ToList().Exists(a=>a.ClientIdNumber==client.ClientIdNumber);
            //int a = Convert.ToInt32(ClientIdNumber);
            //var idnumber = db.Clients.Where(x => x.ClientId == a).FirstOrDefault();
            if (isThisIdExist)
            {
                er++;
                ViewBag.idnumber = "This id is already here";
            }
            bool isThisUsenameExist = db.Clients.ToList().Exists(a => a.ClientUserName == client.ClientUserName);
            if (isThisUsenameExist)
            { 
                er++;
                ViewBag.username = "This Username is already here";
            }

            if (er > 0)
            {
                //idnumber = 0;
                ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
                ViewBag.ScheduleTimeId = new SelectList(db.ScheduleTimes, "ScheduleTimeId", "ScheduleName");
                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var id = db.Clients.Max(p=>p.ClientIdNumber);
                    client.ClientIdNumber = id + 1;
                    db.Clients.Add(client);

                    ClientServiceList list = new ClientServiceList();
                    list.ClientId = client.ClientId;
                    list.ServiceId =Convert.ToInt32( ServiceId);
                    list.Service_Status = true;
                    db.ClientServiceLists.Add(list);

                    ClientBill bill = new ClientBill();
                    bill.ClientId = client.ClientId;
                    bill.BillMonth = client.ClientGymStart;
                    bill.BillStatus = false;
                    var serviceprice = db.Servicesses.Where(x => x.ServiceId == ServiceId).FirstOrDefault().ServieAmount;
                    bill.BillAmount = Convert.ToInt16(serviceprice);
                    bill.DueStatus = 0;
                    db.ClientBills.Add(bill);

                    Schedule schedule = new Schedule();
                    schedule.EmployeeId = Convert.ToInt32(EmployeeId);
                    schedule.ScheduleTimeId = Convert.ToInt32(ScheduleTimeId);
                    schedule.ClientId = client.ClientId;
                    db.Schedules.Add(schedule);
                    db.SaveChanges();
                    //ViewBag.Message = "Registration Sucessful";
                    TempData["Success"] = "Registration Successfully!";
                   // ViewBag.clientid = client.ClientId;
                    return RedirectToAction(actionName: "ClientRegistrationprint", routeValues: new { id = client.ClientId });
                  //  return RedirectToAction("ClientInformation");
                    

                }
            }
            ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
            return View();
        }

        // Client Registration End .....

        public ActionResult ClientRegistrationprint(int?id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Servicess ServiceUpdate = db.Servicesses.Find(id);
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // Client Information Start ....
        public ActionResult ClientInformation(string search)
        {
            int a = Convert.ToInt32(Session["id"]);
            int b = Convert.ToInt32(Session["Designation"]);
            if (a != 0 && b == 1)
            {
                    int i = 0;
                var client = from c in db.Clients select c;
                if (!String.IsNullOrEmpty(search))
                {
                    if (int.TryParse(search, out i))
                    {

                        // int a = Convert.ToInt32(search);
                        client = db.Clients.Where(x => x.ClientIdNumber == i);
                    }
                    else
                    {
                        client = db.Clients.Where(x => x.ClietName == search);
                    }
            }

            return View(client.ToList());
        }
             else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        // Client Information End ......
 

        // Client Update Start ......
        [HttpGet]
        public ActionResult ClientUpdate(int? id) 
        {
            int a = Convert.ToInt32(Session["id"]);
            int b = Convert.ToInt32(Session["Designation"]);
            if (a != 0 && b == 1)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Client ClientUpdate = db.Clients.Find(id);
                if (ClientUpdate == null)
                {
                    return HttpNotFound();
                }
                return View(ClientUpdate);
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        [HttpPost]
        public ActionResult ClientUpdate([Bind(Include = "ClientId,ClietName,ClientIdNumber,ClientContact,ClientMail,ClientAddress,ClientGymStart,ClientUserName,ClientPassword,ClientAdmitionfee")] Client client) 
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ClientInformation");
            }
            return View("ClientUpdate");
        }

        // Client Update End .....


        // Client Service Add Start .....
        public ActionResult ClientServicecAdd()
        {
            int a = Convert.ToInt32(Session["id"]);
            int b = Convert.ToInt32(Session["Designation"]);
            if (a != 0 && b == 1)
            {

            ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
            return View();
        }
              else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        // Client Service Add End .....

        //Client Service List Start 
        public ActionResult ClientServiceList(String search)
        {

            // return View(db.ClientServiceLists.ToList());
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 1)
            {

                int i = 0;
                var client = from c in db.ClientServiceLists select c;
                if (!String.IsNullOrEmpty(search))
                {

                    if (int.TryParse(search, out i))
                    {
                        var id = db.Clients.Where(x => x.ClientIdNumber == i).FirstOrDefault();
                        if (id == null)
                        {
                            ViewBag.message = "Please insert valid client id number ..";
                        }
                        else
                        {
                            int b = Convert.ToInt32(id.ClientId);
                            client = db.ClientServiceLists.Where(a => a.ClientId == b);
                        }
                    }
                    else

GYM Management System/Views/Client/ClientInformation.cshtml
@model IEnumerable<GYM_Management_System.Models.Client>

@{
    ViewBag.Title = "Client Information";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h6>Client Information</h6>
<!--
<ul>
    <li class="list-group-item col-lg-6"><input type="text" class="form-control search-query" placeholder="Search Something"></li>

</ul>
    -->
@*<h2 class="alert-success">@ViewBag.Message</> </h2>*@
    @if (TempData["Success"] != null)
    {
        <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
    }

@*<input style="width:40%" type="text" class="form-control search-query " placeholder="Search Client">*@

@*<h5>  </h5>*@
@using (Html.BeginForm("ClientInformation", "Client", FormMethod.Get))
{
    @Html.TextBox("search")
    <input type="submit" value="submit" />

}
<h5> Client Information table </h5>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClietName)
        </th>
        <th>
            @Html.DisplayName("Client Id Number")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientContact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientGymStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientUserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientAdmitionfee)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClietName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientIdNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientContact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientMail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientGymStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientAdmitionfee)
            </td>
            <td>
                @Html.ActionLink("Update", "ClientUpdate", new { id = item.ClientId })  |
                @Html.ActionLink("New Service Add", "NewServiceAdd", new { id = item.ClientId }) |
            </td>
        </tr>
    }

</table>

GYM Management System/Views/Client/ClientRegistration.cshtml
@model GYM_Management_System.Models.Client

@{
    ViewBag.Title = "Client Registration";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h6>ClientRegistration</h6>
<span class="al"></span>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ClietName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ClietName, new { htmlAttributes = new { @class = "form-control " } })
            @Html.ValidationMessageFor(model => model.ClietName, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.ClientIdNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.ClientIdNumber, new { htmlAttributes = new { @class = "form-control " } })
            @Html.ValidationMessageFor(model => model.ClientIdNumber, "", new { @class = "text-danger" })
            <span class="alert-danger">@ViewBag.idnumber</span>
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.ClientContact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ClientContact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClientContact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClientMail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ClientMail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClientMail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClientAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.TextAreaFor(model => model.ClientAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClientAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClientGymStart, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ClientGymStart, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClientGymStart, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClientUserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ClientUserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClientUserName, "", new { @class = "text-danger" })
            <span class="alert-danger">@ViewBag.username</span>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClientPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.PasswordFor(model => model.ClientPassword, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.ValidationMessageFor(model => model.ClientPassword, "", new { @class = "text-danger" })*@
            <h7 class="text-danger">@ViewBag.password</h7>
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ClientAdmitionfee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.ClientAdmitionfee, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClientAdmitionfee, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Service Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("ServiceId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
            @*@Html.ValidationMessage("Error!!")*@
            <h7 class="text-danger">@ViewBag.ename</h7>
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Schedule Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("ScheduleTimeId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
            @*@Html.ValidationMessage("Error!!")*@
            <h7 class="text-danger">@ViewBag.ScheduleTime</h7>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Employee Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("EmployeeId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
            @*@Html.ValidationMessage("Error!!")*@
            <h7 class="text-danger">@ViewBag.Employee</h7>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-5 col-md-3">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

GYM Management System/Views/Client/ClientRegistrationprint.cshtml
@model GYM_Management_System.Models.Client

@{
    ViewBag.Title = "ClientRegistrationprint";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}
<h2>ClientRegistrationprint</h2>

<h3>Are you sure you want to Print this?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClietName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClietName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientIdNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientIdNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientGymStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientGymStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientAdmitionfee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientAdmitionfee)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Print" class="btn btn-default" /> |
            @Html.ActionLink("Back to Client Registration", "ClientRegistration")
        </div>
    }
</div>

GYM Management System/Views/Client/ClientServiceList.cshtml
@model IEnumerable<GYM_Management_System.Models.ClientServiceList>

@{
    ViewBag.Title = "ClientServiceList";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h2>Client Service List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("ClientServiceList", "Client", FormMethod.Get))
{
    @Html.TextBox("search")
    <input type="submit" value="submit" />

}
<h4 class="alert-danger">@ViewBag.message</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServiceId)
        </th>
        <th>
            @Html.DisplayName("Service Status")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Client.ClietName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Servicess.ServiceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Service_Status)
            </td>
            <td>
                @Html.ActionLink("Service Update", "ClientServiceListUpdate", new { id = item.ClientServiceListId }) |
                @Html.ActionLink("Service Status Update", "ServiceStatusUpdate", new { id = item.ClientServiceListId })
            </td>
        </tr>
    }

</table>