GYM Management System/Models/Expense.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseId { get; set; }
        public string ExpenseProductName { get; set; }
        public string ExpenseProductQuantity { get; set; }
        public int ExpenseProductAmount { get; set; }
        public System.DateTime ExpenseBuyDate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

GYM Management System/Models/Validation/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GYM_Management_System.Models
{
    [MetadataType(typeof(MetadataExpense))]
    public partial class Expense
    {
    }
    public class MetadataExpense
    {
        [Required]
        //[MinLength(3, ErrorMessage = "User Name can't be less than 3 characters")]
        //[MaxLength(100, ErrorMessage = "User Name can't be more than 100 characters")]
        [Display(Name ="Product Name")]
        public string ExpenseProductName { get; set; }

        [Required]
        //[MinLength(1, ErrorMessage = "User Product Quantity can't be less than 1 characters")]
        //[MaxLength(3, ErrorMessage = "User Product Quantity can't be more than 3 characters")]
        [Display(Name ="Product Quantity")]
        public string ExpenseProductQuantity { get; set; }

        [Required]
        //[MinLength(1, ErrorMessage = "User Product Price can't be less than 1 characters")]
        //[MaxLength(4, ErrorMessage = "User Product Price can't be more than 4 characters")]
        [Display(Name ="Product Price")]
        public int ExpenseProductAmount { get; set; }

        [Required]
        [Display(Name ="Expense Buy Datess")]
        [DataType(DataType.Date)]
       // [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime ExpenseBuyDate { get; set; }

        [Required]
        [Display(Name ="Employee Name")]
        public int EmployeeId { get; set; }
    }
}

GYM Management System/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using GYM_Management_System.Models;

namespace GYM_Management_System.Controllers
{
    public class ExpenseController : Controller
    {
        gym_managementEntities db = new gym_managementEntities();
        // GET: Expense
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ExpenseAdd()
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 1)
            {

                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                return View();
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        [HttpPost]
        public ActionResult ExpenseAdd(Expense expense, int? EmployeeId)
        {
            int er = 0;
            if(EmployeeId==null)
            {
                ViewBag.Error = "Please select one item";
                er++;
               
            }
            if (er>0)
            {
                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                return View();
            }
            else
            {
                if(ModelState.IsValid)
                {
                    db.Expenses.Add(expense);
                    db.SaveChanges();
                    return RedirectToAction("ExpenseList");
                    //ViewBag.Messag = "Insert the data";
                }

            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
            return View();
        }

        [HttpGet]
        public ActionResult ExpenseUpdate(int? id)
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 1)
            {

                if (id == null)
                {

                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Expense expense = db.Expenses.Find(id);
                if (expense == null)
                {
                    //ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                    return HttpNotFound();
                }
                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName", expense.EmployeeId);
                return View(expense);
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        [HttpPost]
        public ActionResult ExpenseUpdate([Bind(Include = "ExpenseId,ExpenseProductName,ExpenseProductQuantity,ExpenseProductAmount,ExpenseBuyDate,EmployeeId")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Success"] = "Data Update Successfully";
                return RedirectToAction("ExpenseList");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
            return View("ExpenseUpdate");

        }


        public ActionResult ExpenseList(String FromDate, String ToDate)
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 1)
            {
                //return View(db.Expenses.ToList());
                var expense = from c in db.Expenses select c;
                var ft = Convert.ToDateTime(FromDate).Date;
                DateTime tt = Convert.ToDateTime(ToDate).Date;
                if (ft > tt)
                {
                    ViewBag.message = "Insert valid date";
                }

                else if (!String.IsNullOrEmpty(FromDate) && !String.IsNullOrEmpty(ToDate))
                {
                    
                 
                        expense = db.Expenses.Where(x => x.ExpenseBuyDate >= ft && x.ExpenseBuyDate <= tt);
               
                }
                return View(expense.ToList());
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }
    }
}

GYM Management System/Views/Expense/ExpenseAdd.cshtml
@model GYM_Management_System.Models.Expense

@{
    ViewBag.Title = "ExpenseAdd";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h2>Expense Add</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.ExpenseProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseProductQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.ExpenseProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseProductQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseProductAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.ExpenseProductAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseProductAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseBuyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.ExpenseBuyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseBuyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("EmployeeId", null,"Select One Item", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ExpenseList")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

GYM Management System/Views/Expense/ExpenseList.cshtml
@model IEnumerable<GYM_Management_System.Models.Expense>

@{
    ViewBag.Title = "ExpenseList";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h6>Expense List</h6>
@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}
<h6 class="alert-danger">@ViewBag.message</h6>
<p>
    @Html.ActionLink("Create New", "ExpenseAdd")
</p>
@using (Html.BeginForm("ExpenseList", "Expense", FormMethod.Get))
{ 
    @Html.Label("  From Date")
    @Html.Editor("FromDate")
    @Html.Label("To Date")
    @Html.TextBox("ToDate")
    <input type="submit" value="submit" />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ExpenseProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpenseProductQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpenseProductAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpenseBuyDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee.EmployeeName)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseProductQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseProductAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseBuyDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.EmployeeName)
            </td>
            <td>
                @Html.ActionLink("Update", "ExpenseUpdate", new { id = item.ExpenseId }) |
            </td>
        </tr>
    }
</table>

GYM Management System/Views/Expense/ExpenseUpdate.cshtml
@model GYM_Management_System.Models.Expense

@{
    ViewBag.Title = "ExpenseUpdate";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h2>Expense Update</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="hidden" id="ExpenseId" name="ExpenseId" value="@Model.ExpenseId">
        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseProductQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseProductQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseProductAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseProductAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseProductAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseBuyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseBuyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseBuyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Employee Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form -control" })
                @*@Html.DropDownListFor(model=>model.Employee.EmployeeName, (SelectList)ViewBag.EmployeeID,"Select One Item", htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ExpenseList")
</div>