GYM Management System/Models/ClientServiceList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceList
    {
        public int ClientServiceListId { get; set; }
        public int ClientId { get; set; }
        public int ServiceId { get; set; }
        public bool Service_Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Servicess Servicess { get; set; }
    }
}

GYM Management System/Models/Validation/ClientServiceList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GYM_Management_System.Models
{
    [MetadataType(typeof(MetadataClientServiceList))]
    public partial class ClientServiceList
    {
    }

    public class MetadataClientServiceList
    {
        [Required]
        //[MinLength(5, ErrorMessage = "User Client Name can't be less than 5 characters")]
        //[MaxLength(20, ErrorMessage = "User Client Name can't be more than 20 characters")]
        [Display(Name ="Client Name")]
        public int ClientId { get; set; }

        //[MinLength(10, ErrorMessage = "User Service Name can't be less than 10 characters")]
        //[MaxLength(30, ErrorMessage = "User Service name can't be more than 30 characters")]
        [Required]
        [Display(Name ="Service Name")]
        public int ServiceId { get; set; }

    }
}

GYM Management System/Controllers/ManagerClientController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using GYM_Management_System.Models;

namespace GYM_Management_System.Controllers
{
    public class ManagerClientController : Controller
    {
        gym_managementEntities db = new gym_managementEntities();
        // GET: ManagerClient
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ClientRegistration()
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 2)
            {
                //List<Servicess> serviceList = db.Servicesses.ToList();
                //serviceList.Add(new Servicess() { ServiceId = 0, ServiceName = "Select One" });
                ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
                ViewBag.ScheduleTimeId = new SelectList(db.ScheduleTimes, "ScheduleTimeId", "ScheduleName");
                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                return View();
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }


        [HttpPost]
        public ActionResult ClientRegistration(Client client, int? ServiceId, int? ClientIdNumber, string ClientPassword, int? EmployeeId, int? ScheduleTimeId)
        {
            int er = 0;
            if (ServiceId == null)
            {
                ViewBag.ename = "Select Service Name";
                er++;
            }
            if (ClientPassword == "")
            {
                er++;
                ViewBag.password = "Password Required";
            }
            if (EmployeeId == null)
            {
                er++;
                ViewBag.Employee = "Select Employee Name ";
            }
            if (ScheduleTimeId == null)
            {
                er++;
                ViewBag.ScheduleTime = "Select Schedule Name ";
            }
            bool isThisIdExist = db.Clients.ToList().Exists(a => a.ClientIdNumber == client.ClientIdNumber);
            //int a = Convert.ToInt32(ClientIdNumber);
            //var idnumber = db.Clients.Where(x => x.ClientId == a).FirstOrDefault();
            if (isThisIdExist)
            {
                er++;
                ViewBag.idnumber = "This id is already here";
            }
            bool isThisUsenameExist = db.Clients.ToList().Exists(a => a.ClientUserName == client.ClientUserName);
            if (isThisUsenameExist)
            {
                er++;
                ViewBag.username = "This Username is already here";
            }

            if (er > 0)
            {
                //idnumber = 0;
                ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
                ViewBag.ScheduleTimeId = new SelectList(db.ScheduleTimes, "ScheduleTimeId", "ScheduleName");
                ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var id = db.Clients.Max(p => p.ClientIdNumber);
                    client.ClientIdNumber = id + 1;
                    db.Clients.Add(client);

                    ClientServiceList list = new ClientServiceList();
                    list.ClientId = client.ClientId;
                    list.ServiceId = Convert.ToInt32(ServiceId);
                    list.Service_Status = true;
                    db.ClientServiceLists.Add(list);

                    ClientBill bill = new ClientBill();
                    bill.ClientId = client.ClientId;
                    bill.BillMonth = client.ClientGymStart;
                    bill.BillStatus = false;
                    var serviceprice = db.Servicesses.Where(x => x.ServiceId == ServiceId).FirstOrDefault().ServieAmount;
                    bill.BillAmount = Convert.ToInt16(serviceprice);
                    bill.DueStatus = 0;
                    db.ClientBills.Add(bill);

                    Schedule schedule = new Schedule();
                    schedule.EmployeeId = Convert.ToInt32(EmployeeId);
                    schedule.ScheduleTimeId = Convert.ToInt32(ScheduleTimeId);
                    schedule.ClientId = client.ClientId;
                    db.Schedules.Add(schedule);
                    db.SaveChanges();
                    //ViewBag.Message = "Registration Sucessful";
                    TempData["Success"] = "Registration Successfully!";
                    // ViewBag.clientid = client.ClientId;
                    return RedirectToAction(actionName: "ClientRegistrationprint", routeValues: new { id = client.ClientId });
                    //  return RedirectToAction("ClientInformation");


                }
            }
            ViewBag.ServiceId = new SelectList(db.Servicesses, "ServiceId", "ServiceName");
            return View();
        }

        public ActionResult ClientRegistrationprint(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Servicess ServiceUpdate = db.Servicesses.Find(id);
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        public ActionResult ClientInformation(string search)
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 2)
            {
                int i = 0;
                var client = from c in db.Clients select c;
                if (!String.IsNullOrEmpty(search))
                {
                    if (int.TryParse(search, out i))
                    {

                        // int a = Convert.ToInt32(search);
                        client = db.Clients.Where(x => x.ClientIdNumber == i);
                    }
                    else
                    {
                        client = db.Clients.Where(x => x.ClietName == search);
                    }
                }
                return View(client.ToList());
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        [HttpGet]
        public ActionResult ClientUpdate(int? id)
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 2)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Client ClientUpdate = db.Clients.Find(id);
                if (ClientUpdate == null)
                {
                    return HttpNotFound();
                }
                return View(ClientUpdate);
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        [HttpPost]
        public ActionResult ClientUpdate([Bind(Include = "ClientId,ClietName,ClientIdNumber,ClientContact,ClientMail,ClientAddress,ClientGymStart,ClientUserName,ClientPassword,ClientAdmitionfee")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ClientInformation");
            }
            return View(client);
        }

        public ActionResult ClientServiceList(String search)
        {
            int ab = Convert.ToInt32(Session["id"]);
            int bc = Convert.ToInt32(Session["Designation"]);
            if (ab != 0 && bc == 2)
            {
                // return View(db.ClientServiceLists.ToList());

                int i = 0;
                var client = from c in db.ClientServiceLists select c;
                if (!String.IsNullOrEmpty(search))
                {

                    if (int.TryParse(search, out i))
                    {
                        var id = db.Clients.Where(x => x.ClientIdNumber == i).FirstOrDefault();
                        // int a = Convert.ToInt32(search);
                        // var  a = db.Clients.Find(i).ClientId;
                        //if (id.ClientIdNumber != 0)
                        //{
                        //    int ab =Convert.ToInt32( id.ClientIdNumber);
                        if (id == null)
                        {
                            ViewBag.message = "Please insert valid client id number ..";
                        }
                        else
                        {
                            int b = Convert.ToInt32(id.ClientId);
                            client = db.ClientServiceLists.Where(a => a.ClientId == b);
                        }

                        //client = client1;
                        //}

                    }
                    else
                    {
                        //   client = db.Clients.Where(x => x.ClietName == search);
                    }
                }
                return View(client.ToList());
            }
            else
            {
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Login");
            }
        }

        public ActionResult ClientServiceListUpdate(int? id)
        {
            int ab = Convert.ToInt32(Session["id"]);

GYM Management System/Views/ManagerClient/ClientInformation.cshtml
@model IEnumerable<GYM_Management_System.Models.Client>

@{
    ViewBag.Title = "ClientInformation";
    Layout = "~/Views/Shared/_Manager_Layout.cshtml";
}

<h2>ClientInformation</h2>

@using (Html.BeginForm("ClientInformation", "ManagerClient", FormMethod.Get))
{
    @Html.TextBox("search")
    <input type="submit" value="submit" />
}
<h5> Client Information table </h5>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClietName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientIdNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientContact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientGymStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientUserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientAdmitionfee)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClietName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientIdNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientContact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientMail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientGymStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientAdmitionfee)
            </td>
            <td>
                @Html.ActionLink("Update", "ClientUpdate", new { id = item.ClientId })  |
                @Html.ActionLink("New Service Add", "NewServiceAdd", new { id = item.ClientId }) |
            </td>
        </tr>
    }

</table>

GYM Management System/Views/ManagerClient/ClientRegistration.cshtml
@model GYM_Management_System.Models.Client

@{
    ViewBag.Title = "Client Registration";
    Layout = "~/Views/Shared/_Manager_Layout.cshtml";
}

<h2>ClientRegistration</h2>
<h6>ClientRegistration</h6>
<span class="al"></span>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClietName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ClietName, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.ClietName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.ClientIdNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.ClientIdNumber, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.ClientIdNumber, "", new { @class = "text-danger" })
                    <span class="alert-danger">@ViewBag.idnumber</span>
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ClientContact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ClientContact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientContact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ClientMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextAreaFor(model => model.ClientAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientGymStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ClientGymStart, new { htmlAttributes = new { @class = "form-control", @min=Convert.ToString( DateTime.Now) } })
                @Html.ValidationMessageFor(model => model.ClientGymStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientUserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ClientUserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientUserName, "", new { @class = "text-danger" })
                <span class="alert-danger">@ViewBag.username</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.PasswordFor(model => model.ClientPassword, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.ClientPassword, "", new { @class = "text-danger" })*@
                <h7 class="text-danger">@ViewBag.password</h7>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ClientAdmitionfee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.ClientAdmitionfee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientAdmitionfee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Service Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("ServiceId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessage("Error!!")*@
                <h7 class="text-danger">@ViewBag.ename</h7>
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Schedule Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("ScheduleTimeId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessage("Error!!")*@
                <h7 class="text-danger">@ViewBag.ScheduleTime</h7>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Employee Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("EmployeeId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessage("Error!!")*@
                <h7 class="text-danger">@ViewBag.Employee</h7>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-5 col-md-3">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

GYM Management System/Views/ManagerClient/ClientRegistrationprint.cshtml
@model GYM_Management_System.Models.Client

@{
    ViewBag.Title = "Client Registration Print";
    Layout = "~/Views/Shared/_Manager_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}
<h2>ClientRegistrationprint</h2>

<h3>Are you sure you want to Print this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClietName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClietName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientIdNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientIdNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientGymStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientGymStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientAdmitionfee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientAdmitionfee)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Print" class="btn btn-default" /> |
            @Html.ActionLink("Back to Client Registration", "ClientRegistration")
        </div>
    }
</div>

GYM Management System/Views/ManagerClient/ClientServiceList.cshtml
@model IEnumerable<GYM_Management_System.Models.ClientServiceList>

@{
    ViewBag.Title = "ClientServiceList";
    Layout = "~/Views/Shared/_Manager_Layout.cshtml";
}


<h2>Client Service List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("ClientServiceList", "ManagerClient", FormMethod.Get))
{
    @Html.TextBox("search")
    <input type="submit" value="submit" />

}
<h4 class="alert-danger">@ViewBag.message</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServiceId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Service_Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Client.ClietName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Servicess.ServiceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Service_Status)
            </td>
            <td>
                @Html.ActionLink("Service Update", "ClientServiceListUpdate", new { id = item.ClientServiceListId }) |
                @Html.ActionLink("Service Status Update", "ServiceStatusUpdate", new { id = item.ClientServiceListId })
            </td>
        </tr>
    }

</table>

GYM Management System/Views/ManagerClient/ClientServiceListUpdate.cshtml
@model GYM_Management_System.Models.ClientServiceList

@{
    ViewBag.Title = "ClientServiceListUpdate";
    Layout = "~/Views/Shared/_Manager_Layout.cshtml";
}
<h2>Client ServiceList Update</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>ClientServiceList</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="hidden" id="ClientServiceListId" name="ClientServiceListId" value="@Model.ClientServiceListId" />
        <input type="hidden" id="ClientId" name="ClientId" value="@Model.ClientId" />

        <div class="form-group">
            @Html.Label("Client Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @*@Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.EditorFor(model => model.Client.ClietName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Service Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("ServiceId", null, "Select One Item", htmlAttributes: new { @class = "form-control" })
                @*@Html.EditorFor(model => model.Servicess.ServiceName, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.ServiceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Service_Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Service_Status)
                    @Html.ValidationMessageFor(model => model.Service_Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-6 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ClientServiceList")
</div>

GYM Management System/Views/ManagerClient/ServiceStatusUpdate.cshtml
@model GYM_Management_System.Models.ClientServiceList

@{
    ViewBag.Title = "ServiceStatusUpdate";
    Layout = "~/Views/Shared/_Manager_Layout.cshtml";
}

<h2>Service Status Update</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="hidden" id="ClientServiceListId" name="ClientServiceListId" value="@Model.ClientServiceListId" />
        <input type="hidden" id="ClientId" name="ClientId" value="@Model.ClientId">
        <input type="hidden" id="ServiceId" name="ServiceId" value="@Model.ServiceId">

        <div class="form-group">
            @Html.Label("Service Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Service_Status)
                    @Html.ValidationMessageFor(model => model.Service_Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ClientServiceList")
</div>